-- Seed: comprehensive safety program coverage questions
insert into question_bank (category, question_text, answer_type, is_global, is_required) values
('safety', 'Does your safety program handle Abrasive Blasting/Sandblasting?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Accident Reporting, Investigation & Root Cause Analysis?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Accountability & responsibility for managers, supervisors & employees?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Arc Flash?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Arsenic Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Asbestos Awareness?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Authority to stop work?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Avetta PQF - Safety Management Systems?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Behavioral Based Safety?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Benzene Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Bloodborne Pathogens?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Cadmium Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Chemical Exposure Awareness?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Compressed Gas Cylinders?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Concrete Construction?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Conducting a Hazard Analysis (JSA/JHA/THA)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Confined Space?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Continuous evaluation and revision of policies and procedures?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Crane Operator(s)/Operation?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Demolition?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Disciplinary action?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Diving/Underwater Operations?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Electrical Equipment Grounding Assurance?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Electrical Safety?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Elevated Work Platform (Aerial Lift)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Emergency Action/Emergency Preparedness?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Emergency Planning?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Employee participation?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Ergonomics?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Fall Protection?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Fatigue Management Program?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Fire Prevention program?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle First Aid/CPR?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Fitness for Duty?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Forklift/FLTs?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Ground Disturbance?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Harassment?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Hazard recognition & control?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Health, Safety, & Environmental Program/Policies (safety manual)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Hearing Protection?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Heavy Equipment?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Hexavalent Chromium Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Housekeeping?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Hydrogen Sulfide (H2S) Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Industrial Window Cleaning?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Ionising Radiation Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Journey Management?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Ladder(s)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Lead, Cadmium or Metals Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Lifting/Mobile Equipment/Crane?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Lockout/Tagout (Control of Hazardous Energy)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Management commitment & expectations?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle New Employee or equivalent mentoring program for inexperienced workers?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Periodic health & safety performance appraisals?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Personal Protective Equipment (PPE)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Portable Electrical Power Tools?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Process Safety Management (PSM)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Radio-Frequency Radiation (RF) / Electromagnetic Energy (EME)?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Requirements for management communications?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Resources for meeting health & safety requirements?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Respiratory protection?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Rigging operations?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Safety and Environmental Systems (SEMS) - Offshore Safety?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Safety responsibilities for managers, supervisors & workers?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Scaffolding?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Silica Exposure?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Steel Erection?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Tools/Equipment Inspection and Maintenance?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Tools/Equipment Pre-use Procedures?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Tower Climber Safety?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Tree Trimming and Removal?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Trenching/Shoring/Excavation?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Vehicle Safety/Defensive Driving?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Water Survival/Working Over Water?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Welding, Cutting & Hot Work?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Well Control Procedures?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Wildlife awareness program?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Work Zone Safety?', 'radio_yes_no', true, false),
('safety', 'Does your safety program handle Working alone policy?', 'radio_yes_no', true, false);
